uploads = []

[[generated]]
id = "lKujLlzFux0m6210JM3pt"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "7P2Wmz3EgAl5po0-r29PY"
uri = "file://gastito-qr.png"
type = "image"
title = "Gastito — Expo QR Code"
